- hosts: balancers
  become: yes
  tasks:
  # ------------ Debian --------------
  - name: Executa as ações em Debian
    include_tasks: balancer-debian.yml
    when: ansible_os_family == 'Debian'
  # ------------ Red Hat -------------
  - name: Executa as ações em Red Hat
    include_tasks: balancer-redhat.yml
    when: ansible_os_family == 'RedHat'
  # ------------- Geral --------------
  - name: Garante que o HAProxy esteja presente
    package:
      name: haproxy, keepalived
      state: present
  - name: Garante que o arquivo de configuração esteja presente
    copy:
      src: files/haproxy.cfg
      dest: /etc/haproxy/haproxy.cfg
    register: haproxy
  - name: Garante que o serviço do HAProxy esteja iniciado
    service:
      name: haproxy
      state: started
      enabled: yes
  - name: Garante que o serviço do HAProxy receba as modificações
    service:
      name: haproxy
      state: reloaded
    when: haproxy.changed == true
  - name: Garante que o serviço do keepalived esteja iniciado
    service:
      name: keepalived
      state: started
      enabled: yes
  - name: Garante que o arquivo do keepalived esteja presente
    template:
      src: files/keepalived.conf
      dest: /etc/keepalived/keepalived.conf
    register: keepalived
  - name: Garante que o serviço do keepalived receba as modificações
    service:
      name: keepalived
      state: reloaded
    when: keepalived.changed == true
