- hosts: balancers
  become: yes
  tasks:
  # ------------ Debian --------------
  - name: Executa as ações em Debian
    include_tasks: balancer-debian.yml
    when: ansible_os_family == 'Debian'
  # ------------ Red Hat -------------
  - name: Executa as ações em Red Hat
    include_tasks: balancer-redhat.yml
    when: ansible_os_family == 'RedHat'
  # ------------- Geral --------------
  - name: Garante que o HAProxy esteja presente
    package:
      name: haproxy, keepalived
      state: present
  - name: Garante que o arquivo de configuração do HAProxy esteja presente
    template:
      src: files/haproxy.j2
      dest: /etc/haproxy/haproxy.cfg
    notify: Reload HAProxy
  - name: Garante que o serviço do HAProxy esteja iniciado
    service:
      name: haproxy
      state: started
      enabled: yes
  - name: Garante que o arquivo do keepalived esteja presente
    template:
      src: files/keepalived.conf
      dest: /etc/keepalived/keepalived.conf
    notify: Reload keepalived
  - name: Garante que o serviço do keepalived esteja iniciado
    service:
      name: keepalived
      state: started
      enabled: yes
  - name: Garante que o kernel esteja ajustado para o HAProxy
    lineinfile:
      path: /etc/sysctl.conf
      line: '{{ item }}'
      state: present
    loop:
    - 'net.ipv4.tcp_rmem            = 4096 16060 262144'
    - 'net.ipv4.tcp_wmem            = 4096 16384 262144'
    - 'net.ipv4.tcp_tw_reuse        = 1'
    - 'net.ipv4.ip_local_port_range = 1024 65023'
    - 'net.ipv4.tcp_max_syn_backlog = 60000'
    - 'net.ipv4.tcp_fin_timeout     = 30'
    - 'net.ipv4.tcp_synack_retries  = 3'
    - 'net.ipv4.ip_nonlocal_bind    = 1'
    - 'net.core.somaxconn           = 60000'
    notify: Restart sysctl

  handlers:
  - name: Reload HAProxy
    service:
      name: haproxy
      state: reloaded
  - name: Reload keepalived
    service:
      name: keepalived
      state: reloaded
  - name: Restart sysctl
    service:
      name: systemd-sysctl
      state: restarted
